# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  [push, pull_request]
  
jobs:
 
  Lint:
    name: super-linter
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Lint Code Base
      uses: docker://github/super-linter:v3.15.5
      env:
        VALIDATE_ALL_CODEBASE: true
        JAVASCRIPT_DEFAULT_STYLE: prettier
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
